service: sls-bug-demo
frameworkVersion: '2'

# variablesResolutionMode: 20210326
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    TABLE_NAME:
      'Fn::ImportValue': ${self:service}-deps-${sls:stage}-table-name
    BUCKET_NAME:
      'Fn::ImportValue': ${self:service}-deps-${sls:stage}-bucket-name
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
          Resource:
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE_NAME}"
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE_NAME}/index"
        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource:
            - "arn:aws:s3:::${self:provider.environment.BUCKET_NAME}"

functions:
  names:
    handler: handler.handler
    events:
      - httpApi:
          method: GET
          path: /
