service: sls-bug-demo-deps
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    DOMAIN_PREFIX: ${self:service}-dev
resources:
  Resources:
    Table:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: created_at
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: TableGSI
            KeySchema:
              - AttributeName: user_id
                KeyType: HASH
              - AttributeName: created_at
                KeyType: RANGE
            Projection:
              ProjectionType: KEYS_ONLY
        BillingMode: PAY_PER_REQUEST
        TableName: table-stack-a
    Bucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: sls-bug-demo-bucket-stack-a
  Outputs:
    TableName:
      Value:
        Ref: Table
      Export:
        Name: ${self:provider.environment.DOMAIN_PREFIX}-table-name 
    BucketName:
      Value:
        Ref: Bucket
      Export:
        Name: ${self:provider.environment.DOMAIN_PREFIX}-bucket-name
